In [1]:
#넘파이  - 파이썬: 브로드 캐스팅?이 안됌
#판다스 - 시각화(그래프그리기:히스토그램, 선그래프) 데이터프레임(여러가지 함수)
#크롤링 - 정적페이지, 동적페이지, 셀레늄



In [1]:
import numpy as np

a = np.arange(5) # 0~5
print(type(a))
a

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [10]:
b = np.array([0, 1, 2, 3, 4])

print(b)


[0 1 2 3 4]


[0, 1, 2, 3, 4]

In [16]:
c = [1, 2]
d = [3, 4]

c.extend(d)

print(c)
print(type(c))

[1, 2, 3, 4]
<class 'list'>


In [44]:
c = np.array([np.arange(3), np.arange(3), np.arange(3)])
print(c)
print(c.shape)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.size)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)
2
int32
4
9


In [49]:
a = np.arange(1, 5)
print(a[3])
a[0:5]


4


array([1, 2, 3, 4])

In [4]:
import numpy as np

c = np.array([np.arange(2), np.arange(2)])


c[0,0]= 0
c[0,1]= 1
c[1,0]= 2
c[1,1]= 3
print(c)
print('==========================================')
print(c[1 ,:])#[행, 열]
print('==========================================')

print(c[:, 1:])
print('==========================================')
cc = c[1, :]
print(cc.shape)
print('==========================================')
cc = c[:, 1:]
print(cc.shape)
print('==========================================')
print('==========================================')
print('==========================================')
print('==========================================')




[[0 1]
 [2 3]]
[2 3]
[[1]
 [3]]
(2,)
(2, 1)


In [85]:
a = np.arange(5)

condition = a >= 3
print(condition)


[False False False  True  True]


In [86]:
select = a[condition]
select


array([3, 4])

In [87]:
import numpy as np

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.69087664, -0.84333683, -0.73660285, ..., -1.41579179,
       -0.32211055,  1.23405864])

In [502]:
c = np.array([np.arange(2), np.arange(2, 4, 1)])
c
# c + 2


array([[0, 1],
       [2, 3]])

In [70]:
import numpy as np

# array([1,2],
#      [3,4])
# array([10, 20],
#      [30,40])
# a = [(np.array([1, 2]),np.array([3, 4])

a = np.array([[1, 2],
              [3, 4]])



print (a)
# a [0,0] = 1
# a  [0,1] = 2
# a  [1,0] = 3
# a  [1,1] = 4
print('==========================================')

b = np.array([[10, 20],
              [30, 40]])
print(b)
print('==========================================')


print(a + b)



[[1 2]
 [3 4]]
[[10 20]
 [30 40]]
[[11 22]
 [33 44]]


In [36]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
vector_a @ vector_b

32

In [56]:
np.empty([2, 2])


array([[0.00000000e+000, 1.10384931e-311],
       [1.10384931e-311, 1.10384931e-311]])

In [53]:
np.empty([2,2], dtype = int)

array([[1, 2],
       [3, 4]])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [11]:
import numpy as np

np.zeros((5, ), dtype = np.int64)

array([0, 0, 0, 0, 0], dtype=int64)

In [10]:
x = np.array([1, 2], dtype=np.int64)
print (x)

[1 2]


In [14]:
random = np.random.rand(5)#0,1사이에서 균일 분포 난수 생성
random

array([0.78206148, 0.56909557, 0.08200223, 0.14430502, 0.34553723])

In [16]:
random = np.random.rand(5)#0,1사이에서 균일 분포 난수 생성
random

array([0.28354742, 0.74193858, 0.63800896, 0.13978418, 0.49373358])

In [76]:
np.random.randint(2, size=10)


array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [77]:
a = np.arange(3)
a

array([0, 1, 2])

In [78]:
b = a * 3
b

array([0, 3, 6])

In [79]:
np.array([b, b + 9, b + 18])

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [80]:
a = np.array([1.5, 1.2, 1.7], dtype = np.float32)
a


array([1.5, 1.2, 1.7], dtype=float32)

In [2]:
import numpy as np


In [83]:
b = a.astype(np.int32)
b

array([1, 1, 1])

In [3]:
np.arange(0,6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
np.arange(0,6).reshape(3,2).sum()#행럴 내 모든 원소의 합

15

In [14]:
np.arange(0,6).reshape(3,2).sum(axis = 1) #1축(행) 방향 원소의 합(행의합)

array([1, 5, 9])

In [16]:
np.arange(0,6).reshape(3,2).min(axis = 0) #0축(행) 방향 원소의 합(행의합)

array([0, 1])

In [17]:
np.arange(0,6).reshape(3,2).min(axis = 1) #0축(행) 방향 원소의 합(행의합)

array([0, 2, 4])

In [25]:
a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
print(type(a))
print('==========================================')

print(a.ndim)
print('==========================================')


print(a.itemsize)
print('==========================================')

print(a.size)
print('==========================================')
print('==========================================')


print(a.T)

<class 'numpy.ndarray'>
2
4
15
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [30]:
a = np.arange(15).reshape(3,5)
a[[1,2]]#1번째 행, 2번째 행


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
mask = np.array([0,1,0], dtype = bool)
mask

array([False,  True, False])

In [38]:
a[mask]

array([[5, 6, 7, 8, 9]])

In [34]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
a[~mask] #반전 ~ 키 

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [40]:
mask = a > 0
mask 

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
over0 = a[mask]
over0.shape


(14,)

In [45]:
over1 = a[1][a[1]>6]
over1

array([7, 8, 9])

In [46]:
mask = a[1]>6
mask
over1 = a[1][mask == 1]
over1

array([7, 8, 9])

In [49]:
odd_mask = a % 2 != 0
odd_mask

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [3]:
nn = np.arange(1,25).reshape(6,2,2)#면(explane)0, 행(row)1, 열(column)2
print(nn)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]


In [52]:
nn = np.arange(1,25).reshape(2,6,2)
nn

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [6]:
nn = np.arange(1,25).reshape(6,2,2)#면(explane)0, 행(row)1, 열(column)2
print(nn)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]


In [11]:
nn = np.arange(1,25).reshape(6,2,2)
print(nn.min(axis = 0))

[[1 2]
 [3 4]]


In [12]:
nn = np.arange(1,25).reshape(6,2,2)
print(nn.min(axis = 1))

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]


In [10]:
nn = np.arange(1,25).reshape(6,2,2)
print(nn.min(axis = 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]]


In [2]:
nn = np.arange(1,25).reshape(2,2,2)
print(nn.min(axis=0))
print('==========================================')

print(nn.min(axis=1))
print('==========================================')

print(nn.min(axis=2))
print('==========================================')


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2]
 [13 14]]
[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]


In [15]:
a_arr = np.arange(4)
print(a_arr)
print(a_arr.ndim)
print(a_arr.shape)

[0 1 2 3]
1
(4,)


In [16]:
ra_arr = a_arr.reshape((2,2))
print(ra_arr.ndim)
print(ra_arr.shape)
ra_arr

2
(2, 2)


array([[0, 1],
       [2, 3]])

In [24]:
a_arr = np.arange(4)
print(a_arr)
print('==========================================')
ha_arr = a_arr[np.newaxis, :] #축을 추가할때 1차원 > 2차원

print(ha_arr.ndim)
print('==========================================')
print(ha_arr.shape)
print('==========================================')
print(ha_arr)
print('==========================================')
#축을 없앨때
la_arr = ha_arr.flatten() #평탄화
print(la_arr)



[0 1 2 3]
2
(1, 4)
[[0 1 2 3]]
[0 1 2 3]


In [29]:
arr1 = np.array([1,2,3])
resize_arr1 = np.resize(arr1, (2,4))
resize_arr1

array([[1, 2, 3, 1],
       [2, 3, 1, 2]])

In [27]:
ha_arr

array([[0, 1, 2, 3]])

In [30]:
squeeze_arr = ha_arr.squeeze()#짜내다, 압착 2차원 > 1차원
squeeze_arr

array([0, 1, 2, 3])

In [31]:
squeeze_arr = resize_arr1.squeeze()
squeeze_arr

array([[1, 2, 3, 1],
       [2, 3, 1, 2]])

In [32]:
sq = np.arange(12).reshape(1,1,12)
sq = sq.squeeze()
sq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
arr_1d = np.arange(1, 7)
hiarr_1d = arr_1d.reshape(2,3)
hiarr_1d


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
nn = np.arange(1,25).reshape(2,2,2)
print(nn.min(axis=0))
print('==========================================')

print(nn.min(axis=1))
print('==========================================')

print(nn.min(axis=2))
print('==========================================')


In [60]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print('==========================================')
resahpe3d = arr_2d.reshape((2,3,1))
print(resahpe3d)
print('==========================================')
print('==========================================')
print(arr_2d.min(axis = 0))



[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[1 2 3]


In [63]:
a_arr = np.arange(4)
print(a_arr)
print('==========================================')
ha_arr = a_arr[: ,np.newaxis ] #축을 추가할때 1차원 > 2차원

print(ha_arr.ndim)
print('==========================================')
print(ha_arr.shape)
print('==========================================')
print(ha_arr)#(4,1)
print('==========================================')
#축을 없앨때
la_arr = ha_arr.flatten() #평탄화
print(la_arr)


[0 1 2 3]
2
(4, 1)
[[0]
 [1]
 [2]
 [3]]
[0 1 2 3]


In [74]:
a_arr = np.array([[1,2,3], [4,5,6]])
print('111==========================================')
ha_arr1 = a_arr[: , (0, 1)  , np.newaxis] 
ha_arr = a_arr[: , :  , np.newaxis] 
print(ha_arr1)
print('555==========================================')

print(ha_arr.ndim)#3
print('222==========================================')
print(ha_arr.shape)#2,3,1
print('3333==========================================')
print(ha_arr)
print('4444==========================================')
print(a_arr)

111==========================================
[[[1]
  [2]]

 [[4]
  [5]]]
555==========================================
3
222==========================================
(2, 3, 1)
3333==========================================
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
4444==========================================
[[1 2 3]
 [4 5 6]]


In [78]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr_3d.shape
print(arr_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [79]:
(2,3,3)
resize_3d = np.resize(arr_3d,(2,3,3))
resize_3d
resize_3d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [84]:
a_arr = np.array([[1,2,3],[4,5,6]])
a = a_arr.flatten()
a[0] = 99
print(a)
print(a_arr)


[99  2  3  4  5  6]
[[1 2 3]
 [4 5 6]]


In [85]:
a_arr = np.array([[1,2,3],[4,5,6]])
a = a_arr.ravel()
a[0] = 99
print(a)
print(a_arr)


[99  2  3  4  5  6]
[[99  2  3]
 [ 4  5  6]]


In [87]:
alst = [1,2,3]
blst = alst #그냥대입
blst[0] = 99
print(alst)

[99, 2, 3]


In [92]:
alst = [1,2,[4,5,6]]
blst = alst.copy() #얕은 복사
blst[2][0] = 99
print(alst)


[1, 2, [99, 5, 6]]


In [95]:
import copy
alst = [1,2,[4,5,6]]
blst = copy.deepcopy(alst) #깊은복사
blst[2][0] = 99
print('111==========================================')

print(alst)
print('222==========================================')

print(blst)


111==========================================
[1, 2, [4, 5, 6]]
222==========================================
[1, 2, [99, 5, 6]]


In [96]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [110]:
#horizontal stack
import numpy as np
b = np.hstack([a, a * 3])
print(b)
b.shape


[ 0  1  2  3  4  5  6  7  0  3  6  9 12 15 18 21]


(16,)

In [109]:
#vertical stack
b = np.vstack([a, a * 10])
print(b)
b.shape

[[ 0  1  2  3  4  5  6  7]
 [ 0 10 20 30 40 50 60 70]]


(2, 8)

In [107]:
#deep stack
b = np.dstack([a, a * 10])
print(b)
b.shape

[[[ 0  0]
  [ 1 10]
  [ 2 20]
  [ 3 30]
  [ 4 40]
  [ 5 50]
  [ 6 60]
  [ 7 70]]]


(1, 8, 2)

In [118]:

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])







In [129]:
a = np.hstack((arr1, arr2))
print(a)
print(a.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [130]:
b = np.vstack((arr1, arr2))
print(b)
print(b.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [123]:
c = np.dstack((arr1, arr2))
print(c.shape)

(2, 3, 2)


In [115]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [116]:
print(arr1.T)

[[1 4]
 [2 5]
 [3 6]]


In [134]:
r1 = np.dstack((arr1, arr2))
print(r1)
print("+++++++++++++++++++")
print(r1.shape)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
+++++++++++++++++++
(2, 3, 2)


In [135]:
r2 = np.dstack((arr1 * 10, arr2 * 10))
print(r2)
print(r2.shape)

[[[ 10  70]
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]
(2, 3, 2)


In [133]:
c = np.hstack((r1, r2))
c.shape

(2, 6, 2)

In [127]:
np.vstack((r1, r2))

array([[[  1,   7],
        [  2,   8],
        [  3,   9]],

       [[  4,  10],
        [  5,  11],
        [  6,  12]],

       [[ 10,  70],
        [ 20,  80],
        [ 30,  90]],

       [[ 40, 100],
        [ 50, 110],
        [ 60, 120]]])

In [128]:
np.dstack((r1, r2))

array([[[  1,   7,  10,  70],
        [  2,   8,  20,  80],
        [  3,   9,  30,  90]],

       [[  4,  10,  40, 100],
        [  5,  11,  50, 110],
        [  6,  12,  60, 120]]])

In [138]:
import time
list_a = list(range(1, 1000001))
list_b = list(range(1, 1000001))

# 두 리스트 각 원소 덧셈
start_time = time.time()
result_list = [a + b for a, b in zip(list_a, list_b)]
end_time = time.time()


print("리스트 연산 시간:", end_time - start_time)


# %%
import numpy as np
import time


array_a = np.arange(1, 1000001)
array_b = np.arange(1, 1000001)



리스트 연산 시간: 0.039499759674072266


In [139]:
start_time = time.time()
result_array = array_a + array_b
end_time = time.time()


print("넘파이 배열 연산 시간:", end_time - start_time)



넘파이 배열 연산 시간: 0.006476163864135742


In [140]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [142]:
h = np.hsplit(a, 3)
# h.shape # 에러 
print(h[0].shape) # 리스트안에 0번째가 ndarray

(4, 1)


In [160]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:
nn = np.hsplit(a, 2)
nn

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [173]:
# print(np.hsplit(a,[1, 1])) #0,1, 23
# print("1+++++++++++++++++++")

# print(np.hsplit(a,[1, 2])) #0,e,123
# print("2+++++++++++++++++++")

# print(np.hsplit(a,[2, 1])) #01,e,123
# print("3+++++++++++++++++++")

print(np.hsplit(a,[2, 2])) #01,e,23
print("4+++++++++++++++++++")

# print(np.hsplit(a,[2, 3])) #01,2,3
# print("5+++++++++++++++++++")

print(np.hsplit(a,[3, 1])) #012,e,123
print("6+++++++++++++++++++")

# print(np.hsplit(a,[3, 2])) #012,e,23
# print("7+++++++++++++++++++")

# print(np.hsplit(a,[3, 3])) #012,e,3
# print("8+++++++++++++++++++")




[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([], shape=(4, 0), dtype=int64), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
4+++++++++++++++++++
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([], shape=(4, 0), dtype=int64), array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])]
6+++++++++++++++++++


In [217]:
d = np.dsplit(c, 3)
d

ValueError: dsplit only works on arrays of 3 or more dimensions

In [107]:
from skimage import data
import plotly
import plotly.express as px
import numpy as np

img = data.cells3d()[20:]

# omit some slices that are partially empty
img = img[5:26]

upper_limit = 1.5 * np.percentile(img, q=99)
img = np.clip(img, 0, upper_limit)

fig = px.imshow(
    img,
    facet_col=1,
    animation_frame=0,
    binary_string=True,
    binary_format="jpg",
)
fig.layout.annotations[0]["text"] = "Cell membranes"
fig.layout.annotations[1]["text"] = "Nuclei"
plotly.io.show(fig)

ModuleNotFoundError: The requested file is part of the scikit-image distribution, but requires the installation of an optional dependency, pooch. To install pooch, use your preferred python package manager. Follow installation instruction found at https://scikit-image.org/docs/stable/install.html

In [ ]:
a = np.arange(16).reshape(4,4)
a

In [ ]:
누군가가(미국대학, 연구소) (데이터(x),정답(y)) -> 독립변수(x), 종속변수(target)
x, y >>>>>>> bunch 구조
데이터를 로드 할때 (데이터를 가져온다.)
bunch구조 생김새

In [183]:
import pandas as pd
from sklearn.utils import Bunch

car_data = Bunch()
car_data.feature_names = ['외부 온도', '표면온도', '실내온도', '체온']
car_data.data = np.array([[-1.1, 1.5, 21.4,33.2], [-2.9, 3.0, 23.4, 34.2], [-1.7, 3.2, 25.3, 37.2]]) #np.array( 리스트 )
car_data.target = [0, 0, 0]
car_data.target_names = ['자동차 온도']


car_data['feature_names']

['외부 온도', '표면온도', '실내온도', '체온']

In [209]:
from sklearn import datasets #클래스 함수 변수 될 수 있다
iris = datasets.load_iris()

type(iris)
irisdt = iris['data']#(150,4) vdarray
print(irisdt[:5])
irisdt.shape
iris['feature_names']#sepal 꽃받침 petal 꽃잎



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [216]:
#print(irisdt)
c = irisdt[:, (0,2)]
print(c[:3])

[[5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]]


In [208]:
a = np.hsplit(irisdt,4 )
b = np.hstack((a[1], a[3]))
b[:5]

array([[3.5, 0.2],
       [3. , 0.2],
       [3.2, 0.2],
       [3.1, 0.2],
       [3.6, 0.2]])

In [206]:
a = irisdt[:5].copy()
print(iris['target'])

print("4+++++++++++++++++++")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
4+++++++++++++++++++


<!-- 1. 주어진 리스트를 NumPy 배열로 변환하세요: `[1, 2, 3, 4, 5]`.
2. 0으로 채워진 크기가 5인 정수 배열을 생성하세요.
3. 1부터 10까지의 정수를 가지는 배열을 생성하세요. -->
<!-- 4. 크기가 3x3이고 모든 요소가 1인 2D 배열을 생성하세요. -->
<!-- 5. 주어진 배열의 모든 요소의 합을 계산하세요: `[10, 20, 30, 40]`. -->
<!-- 6. 크기가 3인 단위 행렬을 생성하세요. -->
<!-- 7. 주어진 배열에서 최솟값과 최댓값을 찾으세요: `[3, 8, 1, 6, 2]`. -->
<!-- 8. 주어진 배열의 각 요소를 제곱하세요: `[2, 4, 6, 8]`. -->
<!-- 9. 크기가 4x4이고 1에서 16까지의 숫자로 채워진 2D 배열을 생성하세요. -->
<!-- 10. 주어진 배열의 각 요소에 대해 제곱근을 계산하세요: `[1, 4, 9, 16]`. -->
<!-- 11. 두 배열을 수평으로 결합하세요: `[1, 2, 3]`와 `[4, 5, 6]`. -->
12. 주어진 배열에서 3의 배수를 모두 찾으세요: `[2, 6, 9, 3, 12, 8, 7]`.
13. 크기가 3x3이고 0에서 8까지의 숫자로 채워진 2D 배열을 생성하고, 대각선 요소를 모두 0으로 설정하세요.
14. 주어진 배열의 요소 중에서 5보다 작은 값들을 모두 0으로 설정하세요: `[1, 6, 0, 9, 3, 5]`.
15. 크기가 3인 배열을 생성하고, 해당 배열을 역순으로 정렬하세요.
16. 주어진 배열의 요소 중에서 2로 나누어 떨어지는 값들만 선택하세요: `[1, 4, 6, 8, 10]`.
17. 크기가 5인 랜덤 실수 배열을 생성하세요.
18. 주어진 배열에서 중복된 값을 제거하세요: `[1, 2, 2, 3, 4, 4, 5]`.
19. 두 배열의 내적을 계산하세요: `[1, 2, 3]`와 `[4, 5, 6]`.
20. 크기가 4인 배열에서 각 요소를 2배로 하는 함수를 작성하고, 해당 함수를 배열에 적용하세요.


In [500]:
import numpy as np
# 1
 
a = np.arange(1,6)
print(a)
# 2
print('===================================')
b = np.zeros(5, dtype = int)
print(b)
print('===================================')
# 3
c = np.arange(1, 11)
print(c)
print('===================================')
# 4
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)
print('5===================================')
# 5
e = np.array([10,20,30,40])#행럴 내 모든 원소의 합
sum_e = e.sum()
print(sum_e)
print('6===================================')

#6
# def make(put):
#     for i in range(9):
#         i %= 3
#     return()
f = np.arange(1, 10).reshape(3,3)
f %= 1
for i in range(3):
    f[i, i] = 1


print(f)
print('7===================================')

#7
g = np.array([3, 8, 1, 6, 2])
print(g.min(axis = 0))
print(g.max(axis = 0))
print('8===================================')

#8
h = np.array([2, 4, 6, 8])
for i in range(4):
    jaegob = h[i] * h[i]
    i += 1
    
    print(jaegob)
print('9===================================')
#9
j = np.arange(1, 17).reshape(4,4)
print(j)
print('10===================================')
#10
k = np.array([1, 4, 9, 16])
#제곱근 찾기 실패 다른방법
for i in range(4):
 #   i += 1
    for z in range(2, 4):
        
        #k[i]
        if k[i] % z == 0:
            a = k[i] / z
            print(a)
print('10===================================')
#11
[1, 2, 3]`와 `[4, 5, 6]


[1 2 3 4 5]
[0 0 0 0 0]
[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5===================================
100
6===================================
[[1 0 0]
 [0 1 0]
 [0 0 1]]
7===================================
1
8
8===================================
4
16
36
64
9===================================
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
10===================================
2.0
3.0
8.0


In [517]:
#11
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack([a,b])
print(c)

[1 2 3 4 5 6]


In [168]:
class mybunch:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

In [169]:
bus = mybunch()

In [170]:
bus.a = 10
print(bus.a)

10


In [171]:
texi = mybunch(b=30)
print(texi.b)

30
