In [2]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,3),dtype = int) # np는 기본 float?

array([[1, 1, 1],
       [1, 1, 1]])

In [4]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
import numpy as np
import pandas as pd
df = pd.DataFrame()
df['나이']=[24,25,44]
df['이름']=['aaa','bbb','ccc']
df['주소']=['서울','제주','강남']
df

나이   이름  주소
0  24  aaa  서울
1  25  bbb  제주
2  44  ccc  강남

In [18]:
df4 = pd.DataFrame()
df4['index']=[1,2,4,5]
df4['전화'] = ['010','001','017','019']
df4['혈액형'] = ['A','B','AB','O']
df4 = df4.set_index('전화')

df4

index 혈액형
전화            
010      1   A
001      2   B
017      4  AB
019      5   O

In [20]:
df = pd.read_excel('Day20 Score.xlsx', index_col='번호')
df


국어   영어   수학
번호               
1    60   80   70
2    85   85  100
3   100  100  100
4    80   70   90
5   100   80   90

In [22]:
df.head(2)#5행이 기본

국어  영어   수학
번호             
1   60  80   70
2   85  85  100

In [25]:
df.info()
df.count()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   국어      5 non-null      int64
 1   영어      5 non-null      int64
 2   수학      5 non-null      int64
dtypes: int64(3)
memory usage: 160.0 bytes


국어    5
영어    5
수학    5
dtype: int64

In [30]:
df.describe()#매우중요

국어          영어          수학
count    5.000000    5.000000    5.000000
mean    85.000000   83.000000   90.000000
std     16.583124   10.954451   12.247449
min     60.000000   70.000000   70.000000
25%     80.000000   80.000000   90.000000
50%     85.000000   80.000000   90.000000
75%    100.000000   85.000000  100.000000
max    100.000000  100.000000  100.000000

In [32]:
df['윤리']=80
df['세계사']=[100,80,60,70,90]
df['국영수']=(df['국어']+df['영어']+df['수학'])/3
df


국어   영어   수학  윤리  세계사    국영수
번호                               
1    60   80   70  80  100   70.0
2    85   85  100  80   80   90.0
3   100  100  100  80   60  100.0
4    80   70   90  80   70   80.0
5   100   80   90  80   90   90.0

In [35]:
bdf = pd.DataFrame(index = range(0,4), columns =('미술', '물리'))#데이터 없이 not a number
bdf

미술   물리
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN

In [39]:
df_tot1 = pd.concat([df, bdf])#가로 세로 확장 (열명이 달라서)
df_tot1

국어     영어     수학    윤리    세계사    국영수   미술   물리
1   60.0   80.0   70.0  80.0  100.0   70.0  NaN  NaN
2   85.0   85.0  100.0  80.0   80.0   90.0  NaN  NaN
3  100.0  100.0  100.0  80.0   60.0  100.0  NaN  NaN
4   80.0   70.0   90.0  80.0   70.0   80.0  NaN  NaN
5  100.0   80.0   90.0  80.0   90.0   90.0  NaN  NaN
0    NaN    NaN    NaN   NaN    NaN    NaN  NaN  NaN
1    NaN    NaN    NaN   NaN    NaN    NaN  NaN  NaN
2    NaN    NaN    NaN   NaN    NaN    NaN  NaN  NaN
3    NaN    NaN    NaN   NaN    NaN    NaN  NaN  NaN

In [41]:
df_tot2 = pd.merge(df, bdf, left_index=True, right_index=True)
df_tot2

국어   영어   수학  윤리  세계사    국영수   미술   물리
1   60   80   70  80  100   70.0  NaN  NaN
2   85   85  100  80   80   90.0  NaN  NaN
3  100  100  100  80   60  100.0  NaN  NaN

In [47]:
! pip  pandas



ERROR: unknown command "pandas"


In [42]:
df_tot3 = df.append(bdf)#pandas 2.0삭제

AttributeError: 'DataFrame' object has no attribute 'append'

In [48]:
df_tot4 = df.join(bdf)#df의 row 개수 기준으로 병합
df_tot4

국어   영어   수학  윤리  세계사    국영수   미술   물리
번호                                         
1    60   80   70  80  100   70.0  NaN  NaN
2    85   85  100  80   80   90.0  NaN  NaN
3   100  100  100  80   60  100.0  NaN  NaN
4    80   70   90  80   70   80.0  NaN  NaN
5   100   80   90  80   90   90.0  NaN  NaN

In [49]:
df_tot5 = bdf.join(df)#df의 row 개수 기준으로 병합
df_tot5

미술   물리     국어     영어     수학    윤리    세계사    국영수
0  NaN  NaN    NaN    NaN    NaN   NaN    NaN    NaN
1  NaN  NaN   60.0   80.0   70.0  80.0  100.0   70.0
2  NaN  NaN   85.0   85.0  100.0  80.0   80.0   90.0
3  NaN  NaN  100.0  100.0  100.0  80.0   60.0  100.0

In [55]:
# 연습하기

# 다음 두 데이터 프레임(df2,df4)을 사용하여 결과들을 만드시오

import pandas as pd
df2 = pd.DataFrame()
df2['나이'] = [25,43,22]
df2['이름'] = ['aaa','bbb','ccc']
df2['주소'] = ['서울','제주','강남']
print(df2)
df4 = pd.DataFrame()
df4['index']=[1,2,4,5]
df4['전화'] = ['010','001','017','019']
df4['혈액형'] = ['A','B','AB','O']
df4=df4.set_index("index") 
print(df4)



#-----------이거 다시하기---------------
tt = pd.merge(df2, df4, how='left',left_index=True, right_index=True)
tt
# df2를 기준으로 index 맞춤
#    나이   이름  주소   전화  혈액형
# 0  25  aaa  서울  NaN  NaN
# 1  43  bbb  제주  010    A
# 2  22  ccc  강남  001    B
#df4 를 기준으로 인덱스 맞춤
# index                         
# 1      43.0  bbb   제주  010   A
# 2      22.0  ccc   강남  001   B
# 4       NaN  NaN  NaN  017  AB
# 5       NaN  NaN  NaN  019   O

# 같은 인덱스만 맞추는 경우
#    나이   이름  주소   전화 혈액형
# 1  43  bbb  제주  010   A
# 2  22  ccc  강남  001   B

#양쪽 모두의 조건을 맞추는 경우
#      나이   이름   주소   전화  혈액형
# 0  25.0  aaa   서울  NaN  NaN
# 1  43.0  bbb   제주  010    A
# 2  22.0  ccc   강남  001    B
# 4   NaN  NaN  NaN  017   AB
# 5   NaN  NaN  NaN  019    O



   나이   이름  주소
0  25  aaa  서울
1  43  bbb  제주
2  22  ccc  강남
        전화 혈액형
index         
1      010   A
2      001   B
4      017  AB
5      019   O


나이   이름  주소   전화  혈액형
0  25  aaa  서울  NaN  NaN
1  43  bbb  제주  010    A
2  22  ccc  강남  001    B

In [56]:
df_join = df2.join(df4)#df의 row 개수 기준으로 병합
df_join

나이   이름  주소   전화  혈액형
0  25  aaa  서울  NaN  NaN
1  43  bbb  제주  010    A
2  22  ccc  강남  001    B

In [71]:
df_merge2 = pd.merge(df4,df2, how = 'right', left_index=True, right_index=True)#df의 row 개수 기준으로 병합
df_merge2

전화  혈액형  나이   이름  주소
0  NaN  NaN  25  aaa  서울
1  010    A  43  bbb  제주
2  001    B  22  ccc  강남

In [63]:
df_merge = pd.merge(df2,df4,left_index=True, right_index=True)#가로 세로 확장 (열명이 달라서)
df_merge

나이   이름  주소   전화 혈액형
1  43  bbb  제주  010   A
2  22  ccc  강남  001   B

In [65]:
df_concat = pd.concat([df2,df4])
df_concat

나이   이름   주소   전화  혈액형
0  25.0  aaa   서울  NaN  NaN
1  43.0  bbb   제주  NaN  NaN
2  22.0  ccc   강남  NaN  NaN
1   NaN  NaN  NaN  010    A
2   NaN  NaN  NaN  001    B
4   NaN  NaN  NaN  017   AB
5   NaN  NaN  NaN  019    O

In [73]:
df_merge.to_excel('002_score_sum.xlsx')

In [77]:
df_concat.loc[2,'나이']
df_concat.at[2, '나이']

2    22.0
2     NaN
Name: 나이, dtype: float64

In [78]:
df_concat.iloc[3,3]
df_concat.iat[3,3]

'010'

In [80]:
df_concat.iloc[:3, 1:3]

이름  주소
0  aaa  서울
1  bbb  제주
2  ccc  강남

In [81]:
# df2를 기준으로 index 맞춤
#    나이   이름  주소   전화  혈액형
# 0  25  aaa  서울  NaN  NaN
# 1  43  bbb  제주  010    A
# 2  22  ccc  강남  001    B
tt = pd.merge(df2, df4, how='left',left_index=True, right_index=True) #df2기준으로
tt

나이   이름  주소   전화  혈액형
0  25  aaa  서울  NaN  NaN
1  43  bbb  제주  010    A
2  22  ccc  강남  001    B

In [82]:
tt = df2.join(df4, how='left')
tt

나이   이름  주소   전화  혈액형
0  25  aaa  서울  NaN  NaN
1  43  bbb  제주  010    A
2  22  ccc  강남  001    B

In [83]:
#df4 를 기준으로 인덱스 맞춤
# index                         
# 1      43.0  bbb   제주  010   A
# 2      22.0  ccc   강남  001   B
# 4       NaN  NaN  NaN  017  AB
# 5       NaN  NaN  NaN  019   O
tt = pd.merge(df2, df4, how='right',left_index=True, right_index=True) #df2기준으로
tt
tt = df2.join(df4, how='right')
tt

나이   이름   주소   전화 혈액형
index                         
1      43.0  bbb   제주  010   A
2      22.0  ccc   강남  001   B
4       NaN  NaN  NaN  017  AB
5       NaN  NaN  NaN  019   O

In [84]:
# 같은 인덱스만 맞추는 경우
#    나이   이름  주소   전화 혈액형
# 1  43  bbb  제주  010   A
# 2  22  ccc  강남  001   B
tt = pd.merge(df2, df4, how='inner',left_index=True, right_index=True) #df2기준으로
tt
tt = df2.join(df4, how='inner')
tt

나이   이름  주소   전화 혈액형
1  43  bbb  제주  010   A
2  22  ccc  강남  001   B

In [85]:
tt.loc[2,'나이']  #라벨링(행명명시, 열명 명시 ) 인덱스 
tt.at[2,'나이']

22

In [86]:
#양쪽 모두의 조건을 맞추는 경우
#      나이   이름   주소   전화  혈액형
# 0  25.0  aaa   서울  NaN  NaN
# 1  43.0  bbb   제주  010    A
# 2  22.0  ccc   강남  001    B
# 4   NaN  NaN  NaN  017   AB
# 5   NaN  NaN  NaN  019    O
tt = pd.merge(df2, df4, how='outer',left_index=True, right_index=True) #df2기준으로
tt
tt = df2.join(df4, how='outer')
tt

나이   이름   주소   전화  혈액형
0  25.0  aaa   서울  NaN  NaN
1  43.0  bbb   제주  010    A
2  22.0  ccc   강남  001    B
4   NaN  NaN  NaN  017   AB
5   NaN  NaN  NaN  019    O

In [102]:
tt.to_excel('002_score_sum.xlsx')

In [93]:
tt.loc[1,'주소']=np.nan
tt.iloc[1,2]='독도'
tt2 = tt.fillna(0)
tt2

나이   이름  주소   전화 혈액형
0  25.0  aaa  서울    0   0
1  43.0  bbb  독도  010   A
2  22.0  ccc  강남  001   B
4   0.0    0   0  017  AB
5   0.0    0   0  019   O

In [98]:
tt2.sort_values(by='나이')
tt2.sort_values(by='나이', ascending=False)

tt2.sort_values(by='나이').head(30)['나이']

4     0.0
5     0.0
2    22.0
0    25.0
1    43.0
Name: 나이, dtype: float64

In [103]:
tt2 = pd.read_excel('002_score_sum.xlsx')
tt2.sort_values(by='주소').head(3)['주소']


2    강남
1    독도
0    서울
Name: 주소, dtype: object

In [104]:
tt2['혈액형'].unique()

array([nan, 'A', 'B', 'AB', 'O'], dtype=object)

In [105]:
tt2['혈액형'].value_counts()

혈액형
A     1
B     1
AB    1
O     1
Name: count, dtype: int64

In [227]:
import pandas as pd
import numpy as np

def data_make():
    a = {'반' : [1, 1, 1, 1, 2, 2, 2, 2], 
         '성별' : ['남', '여', '남', '여', '여', '여', '남', '남'],
          '주소' : ['강남','강남','강남','강남','제주','제주','제주','제주'],
         '국어' : [30, 80, 40, 95, 10, 85, 50, 90], 
         '영어' : [75, 80, 92, 90, 80, 60, 88, 70]}
    df = pd.DataFrame(a)
    return df


df= data_make()

df['전공'] = ['문과', '문과','이과', '이과', '이과',  '문과', '문과', '이과']#한번 추가해봄
df


반 성별  주소  국어  영어  전공
0  1  남  강남  30  75  문과
1  1  여  강남  80  80  문과
2  1  남  강남  40  92  이과
3  1  여  강남  95  90  이과
4  2  여  제주  10  80  이과
5  2  여  제주  85  60  문과
6  2  남  제주  50  88  문과
7  2  남  제주  90  70  이과

In [205]:
ta1 = pd.pivot_table(df, values='영어', index=['반'],columns=['전공'],aggfunc=np.mean)
ta1
ta1 = pd.pivot_table(df, values='영어', index=['반'],columns=['전공'],aggfunc='mean')
ta1

전공    문과    이과
반             
1   77.5  91.0
2   74.0  75.0

In [206]:
ta1 = pd.pivot_table(df, values='영어', index=['반'],columns=['전공'],aggfunc=['mean','sum'])
ta1

mean        sum     
전공    문과    이과   문과   이과
반                       
1   77.5  91.0  155  182
2   74.0  75.0  148  150

In [207]:
ta1 = pd.pivot_table(df, values=['영어','국어'], index=['반'],columns=['전공','성별'],aggfunc='mean')
ta1

국어              영어            
전공  문과      이과      문과      이과    
성별   남   여   남   여   남   여   남   여
반                                 
1   30  80  40  95  75  80  92  90
2   50  85  90  10  88  60  70  80

In [208]:
df


반 성별  주소  국어  영어  전공
0  1  남  강남  30  75  문과
1  1  여  강남  80  80  문과
2  1  남  강남  40  92  이과
3  1  여  강남  95  90  이과
4  2  여  제주  10  80  이과
5  2  여  제주  85  60  문과
6  2  남  제주  50  88  문과
7  2  남  제주  90  70  이과

In [209]:
#9번행 국어점수를 90 > nan
df.loc[9,'국어']=np.nan


In [224]:
ta1 = pd.pivot_table(df, values=['영어','국어'], index=['반'],columns=['전공','성별'],aggfunc='mean'
                    ,fill_value=0)
ta1
ta1 = pd.pivot_table(df, values=['영어','국어'], index=['반'],columns=['전공','성별'],aggfunc='mean')
ta1


국어              영어            
전공  문과      이과      문과      이과    
성별   남   여   남   여   남   여   남   여
반                                 
1   30  80  40  95  75  80  92  90
2   50  85  90  10  88  60  70  80

In [211]:
df

반   성별   주소    국어    영어   전공
0  1.0    남   강남  30.0  75.0   문과
1  1.0    여   강남  80.0  80.0   문과
2  1.0    남   강남  40.0  92.0   이과
3  1.0    여   강남  95.0  90.0   이과
4  2.0    여   제주  10.0  80.0   이과
5  2.0    여   제주  85.0  60.0   문과
6  2.0    남   제주  50.0  88.0   문과
7  2.0    남   제주  90.0  70.0   이과
9  NaN  NaN  NaN   NaN   NaN  NaN

In [212]:
nn = pd.DataFrame([30,30,np.nan,33])
nn.mean() #nan제외(값도 개수제외)하고 
nn.mean(skipna=False)




0   NaN
dtype: float64

In [213]:
df


반   성별   주소    국어    영어   전공
0  1.0    남   강남  30.0  75.0   문과
1  1.0    여   강남  80.0  80.0   문과
2  1.0    남   강남  40.0  92.0   이과
3  1.0    여   강남  95.0  90.0   이과
4  2.0    여   제주  10.0  80.0   이과
5  2.0    여   제주  85.0  60.0   문과
6  2.0    남   제주  50.0  88.0   문과
7  2.0    남   제주  90.0  70.0   이과
9  NaN  NaN  NaN   NaN   NaN  NaN

In [214]:
df.loc[9, '국어']=90
df

반   성별   주소    국어    영어   전공
0  1.0    남   강남  30.0  75.0   문과
1  1.0    여   강남  80.0  80.0   문과
2  1.0    남   강남  40.0  92.0   이과
3  1.0    여   강남  95.0  90.0   이과
4  2.0    여   제주  10.0  80.0   이과
5  2.0    여   제주  85.0  60.0   문과
6  2.0    남   제주  50.0  88.0   문과
7  2.0    남   제주  90.0  70.0   이과
9  NaN  NaN  NaN  90.0   NaN  NaN

In [215]:
seO = df.groupby('전공')['영어'].mean()
seO

전공
문과    75.75
이과    83.00
Name: 영어, dtype: float64

In [216]:
se1 = df.groupby(['전공','주소'])['영어'].mean()
se1

전공  주소
문과  강남    77.5
    제주    74.0
이과  강남    91.0
    제주    75.0
Name: 영어, dtype: float64

In [217]:
type(df.iloc[0])

pandas.core.series.Series

In [228]:
df.groupby(['반','주소']).size()
df.groupby(['반']).size()
df.groupby(['반']).count()
df['성별'].sum()
df.sum()

반                   12
성별            남여남여여여남남
주소    강남강남강남강남제주제주제주제주
국어                 480
영어                 635
전공    문과문과이과이과이과문과문과이과
dtype: object

In [229]:
df

반 성별  주소  국어  영어  전공
0  1  남  강남  30  75  문과
1  1  여  강남  80  80  문과
2  1  남  강남  40  92  이과
3  1  여  강남  95  90  이과
4  2  여  제주  10  80  이과
5  2  여  제주  85  60  문과
6  2  남  제주  50  88  문과
7  2  남  제주  90  70  이과

In [ ]:
import pandas as pd
s = pd.Series(['banana', 42])
print(s)

In [ ]:
s = pd.Series(['이순신', '거북선'])
print(s)

In [ ]:
s = pd.Series(['이순신', '거북선'], index=['누가', '무엇'])
print(s)

In [231]:
index = pd.MultiIndex.from_tuples([('A', 1), ('A', 2), ('B', 1), ('B', 2)], names=['first', 'second'])
values = [10, 20, 30, 40]
multi_index_series = pd.Series(values, index=index)

print(multi_index_series)

first  second
A      1         10
       2         20
B      1         30
       2         40
dtype: int64


In [245]:
import pandas as pd
import random
import numpy as np
from datetime import datetime, timedelta
names = ['철수', '영희', '민수', '수현', '지영']
jobs = ['개발자', '디자이너', '마케터', '회계사', '경영자']
random_jobs = [random.choice(jobs) for _ in range(len(names))]
start_date = datetime(1970, 1, 1)
end_date = datetime(2000, 12, 31)
random_birthdays = [start_date +
                    timedelta(days=np.random.randint(1, (end_date - start_date).days)) for _ in range(len(names))]


random_birthdays


[datetime.datetime(1970, 8, 12, 0, 0),
 datetime.datetime(1977, 9, 11, 0, 0),
 datetime.datetime(1978, 12, 5, 0, 0),
 datetime.datetime(1975, 5, 4, 0, 0),
 datetime.datetime(1998, 1, 1, 0, 0)]

In [246]:
random_birthdays = [date.strftime('%Y-%m-%d') for date in random_birthdays] # "string format time"


start_date = datetime(2010, 1, 1)
end_date = datetime(2023, 1, 1)
random_hire_dates = [start_date + timedelta(days=np.random.randint(1, (end_date - start_date).days)) for _ in range(len(names))]#SPT
random_hire_dates = [date.strftime('%Y-%m-%d') for date in random_hire_dates] #"string format time"

data = {
    '이름': names,
    '직업': random_jobs,
    '생일': random_birthdays,  # "string format time"
    '입사일': random_hire_dates,#"string format time"
    # '나이': random_ages
}

df = pd.DataFrame(data)
df

이름    직업          생일         입사일
0  철수   개발자  1970-08-12  2016-09-07
1  영희   개발자  1977-09-11  2013-12-06
2  민수   회계사  1978-12-05  2018-09-18
3  수현   경영자  1975-05-04  2018-01-18
4  지영  디자이너  1998-01-01  2015-08-21

In [247]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      5 non-null      object
 1   직업      5 non-null      object
 2   생일      5 non-null      object
 3   입사일     5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes


In [248]:
df.columns

Index(['이름', '직업', '생일', '입사일'], dtype='object')

In [249]:
df['생일']=pd.to_datetime(df['생일'])
df['입사일']=pd.to_datetime(df['입사일'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   이름      5 non-null      object        
 1   직업      5 non-null      object        
 2   생일      5 non-null      datetime64[ns]
 3   입사일     5 non-null      datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 292.0+ bytes


In [250]:
today = datetime.now()
df['나이']=((today-df['생일']).dt.days//365)
df

이름    직업         생일        입사일  나이
0  철수   개발자 1970-08-12 2016-09-07  53
1  영희   개발자 1977-09-11 2013-12-06  46
2  민수   회계사 1978-12-05 2018-09-18  45
3  수현   경영자 1975-05-04 2018-01-18  48
4  지영  디자이너 1998-01-01 2015-08-21  26

In [251]:
df['첫월급']=((df['입사일']-df['생일']).dt.days//365)
df


이름    직업         생일        입사일  나이  첫월급
0  철수   개발자 1970-08-12 2016-09-07  53   46
1  영희   개발자 1977-09-11 2013-12-06  46   36
2  민수   회계사 1978-12-05 2018-09-18  45   39
3  수현   경영자 1975-05-04 2018-01-18  48   42
4  지영  디자이너 1998-01-01 2015-08-21  26   17

In [254]:
df = pd.DataFrame(
    data={'직업': ['꾸러기', '동네아저씨','조종사','간호사','음악가','법무사','세무사'], 
          '생일': ['1988-04-22', '2008-04-22', '1999-11-22', '2001-08-12', '1993-04-30', '1987-04-17', '2005-04-05'], 
          '입사일': ['1994-10-22', '2022-11-21', '2020-01-22', '2016-08-22', '2012-02-22', '2021-09-08', '2018-11-24'], 
          '나이': [36, 26, 35, 23,31 , 37, 18]}, 
    index=['둘리', '고길동','탐','다수','판다스','스파이더','댕댕이'],
    columns=['직업', '생일', '입사일', '나이']) 

df

직업          생일         입사일  나이
둘리      꾸러기  1988-04-22  1994-10-22  36
고길동   동네아저씨  2008-04-22  2022-11-21  26
탐       조종사  1999-11-22  2020-01-22  35
다수      간호사  2001-08-12  2016-08-22  23
판다스     음악가  1993-04-30  2012-02-22  31
스파이더    법무사  1987-04-17  2021-09-08  37
댕댕이     세무사  2005-04-05  2018-11-24  18

In [255]:
df.to_csv('006_ageError_emp.csv')

In [257]:
df2 = pd.read_csv('006_ageError_emp.csv')
df2

Unnamed: 0     직업          생일         입사일  나이
0         둘리    꾸러기  1988-04-22  1994-10-22  36
1        고길동  동네아저씨  2008-04-22  2022-11-21  26
2          탐    조종사  1999-11-22  2020-01-22  35
3         다수    간호사  2001-08-12  2016-08-22  23
4        판다스    음악가  1993-04-30  2012-02-22  31
5       스파이더    법무사  1987-04-17  2021-09-08  37
6        댕댕이    세무사  2005-04-05  2018-11-24  18

In [268]:
df2.rename(columns={'Unnamed: 0': '이름'}, inplace=True)

In [269]:
df2.set_index('이름', inplace=True)

KeyError: "None of ['이름'] are in the columns"

In [271]:
df2

직업          생일         입사일  나이
이름                                     
둘리      꾸러기  1988-04-22  1994-10-22  36
고길동   동네아저씨  2008-04-22  2022-11-21  26
탐       조종사  1999-11-22  2020-01-22  35
다수      간호사  2001-08-12  2016-08-22  23
판다스     음악가  1993-04-30  2012-02-22  31
스파이더    법무사  1987-04-17  2021-09-08  37
댕댕이     세무사  2005-04-05  2018-11-24  18

index.values 속성 keys 메서드

In [273]:
df.index

Index(['둘리', '고길동', '탐', '다수', '판다스', '스파이더', '댕댕이'], dtype='object')

In [274]:
df.columns

Index(['직업', '생일', '입사일', '나이'], dtype='object')

In [275]:
df.keys()

Index(['직업', '생일', '입사일', '나이'], dtype='object')

In [276]:
df.index[0]

'둘리'

In [277]:
df.dtypes

직업     object
생일     object
입사일    object
나이      int64
dtype: object

In [280]:
age = df['나이']
age.mean()
age.max()
age.min()
age.std()

7.2768386647211685

In [279]:
age[age>age.mean()]

둘리      36
탐       35
판다스     31
스파이더    37
Name: 나이, dtype: int64

In [285]:
df['생일']= df['생일'].astype(str) #datetime > string(object)
df['생일'] = pd.to_datetime(df['생일']) #datetime << string(object)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 둘리 to 댕댕이
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   직업      7 non-null      object        
 1   생일      7 non-null      datetime64[ns]
 2   입사일     7 non-null      object        
 3   나이      7 non-null      int64         
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 280.0+ bytes


In [286]:
df['생일'].dt.year
df['생일'].dt.month
df['생일'].dt.day

둘리      22
고길동     22
탐       22
다수      12
판다스     30
스파이더    17
댕댕이      5
Name: 생일, dtype: int32

In [151]:
#df.전공 = type(df['전공'])

In [115]:
save_path = '004_ban_sunjiuk,addr_kor_eng.xlsx'
df['index']=[0,1,2,3,4,5,6,9]
df = df.set_index('index')
df
df.to_excel(save_path)

In [110]:
df.dtypes
df.info()
df.count()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   반       8 non-null      int64 
 1   성별      8 non-null      object
 2   주소      8 non-null      object
 3   국어      8 non-null      int64 
 4   영어      8 non-null      int64 
 5   전공      8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes


반         국어         영어
count  8.000000   8.000000   8.000000
mean   1.500000  60.000000  79.375000
std    0.534522  31.735514  10.888231
min    1.000000  10.000000  60.000000
25%    1.000000  37.500000  73.750000
50%    1.500000  65.000000  80.000000
75%    2.000000  86.250000  88.500000
max    2.000000  95.000000  92.000000